### ISSUE TITLE
Leading Edges

### ISSUE THREAD

**Issue by gregkoytiger** [ctlab/fgsea#1]
Really great code Alexei, one missing feature that would be greatly helpful and should not be too difficult to implement is to return the leading edge genes (http://software.broadinstitute.org/gsea/doc/GSEAUserGuideTEXT.htm#_Running_a_Leading) for the pathway to understand the genes that drive the enrichment. The R code to do something like this should be along the lines of:

if(maxP > -minP) {
  leadingEdge <- names(geneList[1:which(runningScore == maxP)])
    leadingEdge <- leadingEdge[leadingEdge %in% geneSet]
    leadingEdge <- paste0(leadingEdge, collapse='|')
}else{
   leadingEdge <- names(geneList[which(runningScore == minP):
                                    length(geneList)])
    leadingEdge <- laggingEdge[leadingEdge %in% geneSet]
    leadingEdge <- paste0(leadingEdge, collapse='|')
}

**Comment by assaron** [comment]
Greg, good point. I'll implement it soon.

**Comment by assaron** [comment]
Greg, if you check out the [dev](https://github.com/ctlab/fgsea/tree/dev) branch, there will be a `leadingEdge` column in table returned by `fgsea`.

**Comment by gregkoytiger** [comment]
Awesome, thank you Alexey for the rapid implementation!

**Comment by apugalde** [comment]
Thanks for this great package, Alexey. Just one suggestion about the leading edge genes. 
If I am not wrong, with the actual code, if ScoreType = neg but maxP > -minP, the leading edge list does not return the genes that contribute to the reported genesetStatistic (which is minP). Maybe it would be desirable that if ScoreType = neg, the leading edge genes are those to the right of min ES, independently that max P > -minP. Likewise, if ScoreType = pos, the leading edge list should report the genes  to the left of max ES, independently that maxP < -minP.

**Comment by assaron** [comment]
@apugalde thanks, you're right, I've fixed the behavior in the master branch

**Comment by cfoguet** [comment]
I am not sure if its intentional, but in the code (calcGseaStat) leading edge is derived from bottoms (which.max(bottoms) even when ES is positive (maxP > -minP). This can lead to the leading edge including genes to the right of ES (maxP) contrary to the definition of leading edge genes. 

This also means that running fgsea with sign inverted data will lead to different leading edge genes. For instance   

fgseaRes <- fgsea(pathways = examplePathways, 
                  stats    = exampleRanks,
                  eps      = 0.0,
                  minSize  = 15,
                  maxSize  = 500)


fgseaRes_rev <- fgsea(pathways = examplePathways, 
                  stats    = exampleRanks*-1,
                  eps      = 0.0,
                  minSize  = 15,
                  maxSize  = 500)

 fgseaRes$ES will be equal to -1*fgseaRes_rev$ES but leading edges will be different

**Comment by assaron** [comment]
@cfoguet good call, thank you, it does look like a bug
