### ISSUE TITLE
Question: unbalanced gene-level statistic warning

### ISSUE THREAD

**Issue by TatiKarp** [ctlab/fgsea#124]
Hello! Thank you for the development and maintenance of this project! 

When using `fgsea` function I got a warning: 

```
In fgseaMultilevel(...) :
  There were 1 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 100000)
```
Increasing the nPermSimple still results in the same warning. 
So what exactly is this warning about and why does it prevent the function from calculating the statistics? 

Thank you in advance!

**Comment by assaron** [comment]
When the input statistic is unbalanced (skewed towards positive or negative values) it's hard to accurately estimate two-tailed GSEA p-value. By Subramanian et al it is normalized by the probability of a random gene set to have negative or positive score, which can be very low and hard to estimate for unbalanced statistic values. 

How exactly did you get this ranks? Do you want to have a two-tailed test, or a one-tailed test would suffice? One-tailed test could be more and don't have this problem. They can be triggered by setting `scoreType="pos"` or `scoreType="neg"` depending whether you are looking for a positive or negative enrichment.

**Comment by TatiKarp** [comment]
Thank you, 
I created the ranks based on a list of differentially expressed genes using this metric: -10logFDR * (+/- from FC).
Based on this ranking I have 8015 positive values and 9141 negative values. Do you think this difference can cause unbalance?

**Comment by shnuggles** [comment]
I have a related question about this error (I hope it's ok that I place it here). I am getting this error while using logFC, but in my case the input statistic is pretty unbalanced (80% up; 20% down). My question is why isn't the NES being calculated in this case? Maybe I'm misunderstanding how NES is calculated or how the unbalanced input creates uncertainty.  

Just to explain my intended use, I was hoping to use NES as a quantitative score for each gene set and for all of my samples. Essentially, I want to use it to create a sample x gene set matrix. Obviously, I would prefer not to have missing values so I am wondering if the NES can be calculated or assigned some value instead of being missing.

**Comment by assaron** [comment]
> Thank you, I created the ranks based on a list of differentially expressed genes using this metric: -10logFDR * (+/- from FC). Based on this ranking I have 8015 positive values and 9141 negative values. Do you think this difference can cause unbalance?

@TatiKarp  I don't think logFDR is a good choice of the metric, try to use logPvalue instead, or statistic value from differential gene expression test

**Comment by assaron** [comment]
> I have a related question about this error (I hope it's ok that I place it here). I am getting this error while using logFC, but in my case the input statistic is pretty unbalanced (80% up; 20% down). My question is why isn't the NES being calculated in this case? Maybe I'm misunderstanding how NES is calculated or how the unbalanced input creates uncertainty.

@shnuggles NES is calculated by dividing the enrichment score of the gene set by the average ES value of the same sign. In your case, I guess, it's hard to generate a sample of gene sets with negative ES values, thus we can't calculate average value and can't calculate NES. 

A workaround for that could be to just run a one-tailed test, specifying `scoreType="pos"`, there only positive direction of the enrichment is considered, and it becomes much simple computationally.

**Comment by TatiKarp** [comment]
> 
@assaron thank you for your suggestion. I am using FDR values from differential gene expression test, it will produce the same ranks as nominal p-values. Why do you think this is not the right way?

**Comment by TatiKarp** [comment]
@shnuggles If I can suggest you something: You can check GSVA analysis to create a sample x gene set matrix.  https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-14-7

**Comment by assaron** [comment]
@VitorAguiar 

> but using logFC from edgeR as my statistic.

First of all, I don't recommend using logFC for ranking genes, unless it's a shrinked estimator like the one you can get with `DESeq2::lfcShrink`. I'm not sure if edgeR has something like this. Ranking by statistic or logPval*sign(logFC) should better prioritize important changes.

> I noticed that using "nperm" or "nPermSimple" results in widely different pvalues in this case. Using nperm, even though nMoreExtreme is 0, pval is still 0.002. Using nPermSimple, pval is 10^-28.

`nperm` and `nPermSimple` are different options. `nperm` is there only for the backward compatibility and shouldn't be used (actually, maybe we should remove it from `fgsea` at all) — it's presence triggers the usage of `fgseaSimple` method, which can't estimate small p-values well, that's why you have the p-value of 0.002 instead of 1e-28. 

However, `fgseaSimple` is used internally by `fgseaMultilevel()` as the first-pass estimation, before refinement with the multilevel approach. `nPermSimple` controls the number of permutations in that first pass. This first pass also estimates the denominator of GSEA P-value, which was originally defined (for positive enrichment scores) as: probability of a random gene set to have the enrichment score at least x divided by the probability of the gene set to have positive enrichment score. For unbalanced statistic the denominator can be small, and higher values of `npermSimple` are needed to resolve it. Thus the work-around suggestion shown in the warning.

That said, I'm not quite sure that there is a good way to define a two-tailed enrichment test where your statistic is unbalanced. Historically, the above denominator was proposed, but I don't think anyone checked careful enough that it works as expected in the extreme cases, where it is so much different from balanced 0.5. Using two separate tests for positive and negative enrichment with `scoreType="pos"` and `scoreType="neg"` could be more appropriate.
