### ISSUE TITLE
fgsea is not reproducible on Windows and OSX

### ISSUE THREAD

**Issue by assaron** [ctlab/fgsea#13]
For some reason fgsea when used in parallel mode on Windows and OSX doesn't respect seed settings. See test failed at https://ci.appveyor.com/project/assaron/fgsea/build/1.0.27#L1265 and https://travis-ci.org/ctlab/fgsea/jobs/318271040#L4562

**Comment by kohlkopf** [comment]
This issue was closed erroneously. Stable results are not produced on macOS. Running

`library(fgsea)`
`data("examplePathways")`
`data("exampleRanks")`
`set.seed(42)`
`print(sample.int(10^9, 1))`
`print(fgsea(examplePathways[1:2], exampleRanks, nperm=2000, maxSize=500, nproc=1)$nMoreExtreme)`
`print(sample.int(10^9, 1))`

produces

`> print(sample.int(10^9, 1))`
`[1] 707850213`
`> print(fgsea(examplePathways[1:2], exampleRanks, nperm=2000, maxSize=500, nproc=1)$nMoreExtreme)`
`[1] 634 782`
`> print(sample.int(10^9, 1))`
`[1] 578398257`
