### ISSUE TITLE
Does fGSEA require minSize as well?

### ISSUE THREAD

**Issue by MEladawi** [ctlab/fgsea#130]
Hi--

I wanted to inquire if fGSEA Monte Carlo based p-value also requires minSize of 15-25 like the original GSEA to prevent the p-value inflation? or we can use it with smaller sets?

Best,

**Comment by assaron** [comment]
We don't have any hard data, but we do recommend to set certain minSize value (may be incorrectly). I usually use 15, but occasionally use lower values for some  pathway collections, when there are potentially interesting gene sets of small size. Otherwise small gene sets frequently have high non-significant nominal P-value, which decreases the overall power due to Benjamini-Hochber multiple hypotheses testing correction.
