### ISSUE TITLE
fgseaMultilevel() hangs with some pathway/gene combinations

### ISSUE THREAD

**Issue by igordot** [ctlab/fgsea#57]
I successfully ran fgsea many times. I finally ran into a problem. One particular pathway and gene list combination causes fgsea to hang. I am just going to include a reproducible example.

Set up the environment (includes one ranked gene list and a list of four pathways):
```
library(fgsea)
library(BiocParallel)
register(SerialParam())

download.file("https://www.dropbox.com/s/e6lgirf3xt1b3to/fgsea-pathways.rds?raw=1", "fgsea-p.rds")
download.file("https://www.dropbox.com/s/8znl53ha7wylvdc/fgsea-stats.rds?raw=1", "fgsea-s.rds")

fgseap = readRDS("fgsea-p.rds")
fgseas = readRDS("fgsea-s.rds")
```

The original `fsgea()` method works:
```
fgsea_res = fgsea(pathways = fgseap, stats = fgseas, nperm = 1000)
```

Using `fgseaMultilevel()` method works if you skip the second pathway:
```
fgsea_res = fgseaMultilevel(pathways = fgseap[c(1,3,4)], stats = fgseas)
```

Randomly subsetting the genes works (from about 20k to 10k):
```
fgsea_res = fgseaMultilevel(pathways = fgseap, stats = sample(fgseas, 10000))
```

Including all the pathways and all the genes makes it hang (the command runs forever):
```
fgsea_res = fgseaMultilevel(pathways = fgseap, stats = fgseas)
```

I tried this on two different systems with different fgsea versions (1.10.0 and 1.11.1) and it happens on both.

**Comment by assaron** [comment]
Hi,

In the github version and the one recently released in Bioconductor (1.12) it doesn't hang and finishes with the warning. The problem tthere is that your stats are skewed towards positive values. Thus it's hard to calculate p-values for negatively enriched gene sets, as it requires calculation of probability of gene set to have negative enrichment which is very low. The "original" method now also features this warning as it has the same problem of unreliable p-value calculation is this case.

Where are these stats are coming from? Do you really want to find negatively enriched pathways in this case?

**Comment by igordot** [comment]
Not sure I understand. My stats have 10103 negative and 10430 positive values. There are a few very positive outliers (220 > 3, but only 1 < -3).

The stats are coming from differential expression results. I have had datasets that are far more skewed. In all cases, I would like to see both directions if possible.

If skewing is the problem, why does subsetting the same list not cause problems? Is it just a few genes that are problematic?

I should add there were thousands of pathways in my original list. I subset the list because only one managed to hang the system.

**Comment by assaron** [comment]
Skewed means that probability of a random gene set to have a negative score is small. In this case it's about 1e-6: you can run `z <- replicate(1e5, calcGseaStat(fgseas, sample.int(length(fgseas), 500)))` and check that there will be zero negative scores. 

As we follow the original definition of P-value by Subramanian et al, it's calculated as probability of a random gene set to have more extreme score divided by the probability of a gen set to have the score of the same sign. As fgsea was not designed to handle such situations properly (as well as Broad version), we just throw a warning. That's why I'm asking where these stats come to understand in what scenarios can lead to this and how much implementation of the proper handling is warranted (it will make the code messier). It doesn't look like stats from normal RNA-seq differential expression. If you don't like to share them in public you can send me more elaborate info to e-mail alsergbox@gmail.com

Subsetting works as in these cases the offending gene set becomes positively enriched (with ES > 0), which eliminates the requirement to normalize for random gene sets to have negative ES.

**Comment by igordot** [comment]
Thank you for clarifying.

I tried version 1.12.0 and the problematic behavior is resolved. The pathway that was causing the problem now returns NA for all stats except ES.
