### ISSUE TITLE
fgsea never stops running

### ISSUE THREAD

**Issue by johnse** [ctlab/fgsea#78]
I'm trying to run fgsea on a subset of data from a dataset. I've used it before on a different subset with no problem but now when I try to run it:

```
MCbtoEVnew.gsea <- fgseaMultilevel(pathways = pathways.interest, 
                                stats = MCbtoEVnew.markers.human) %>%
  mutate(log10pval = -log10(pval)) %>%
  arrange(-NES)
```

it just keeps running indefinitely without returning a result. If I stop it I get the following error: 

Error: no more error handlers available (recursive errors?); invoking 'abort' restart

I've tried re-starting rstudio and re loading all data but it doesn't help. I also have tried to run it on old gene lists that worked previously and it does the same thing. 

```sessionInfo("fgsea")
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
character(0)

other attached packages:
[1] fgsea_1.14.0

**Comment by assaron** [comment]
Can you try the version from GitHub (1.15.2)? I think there was a bug with
infinite loop, that was fixed in that version.

**Comment by ChristianRohde** [comment]
Hi, 

I used fgsea for a long time with settings like fgsea(pathways = examplePathways, stats = exampleRanks, minSize = 15, maxSize = 500, nperm = 10000). It used to be very fast indeed. Now I have problems since fgsea does not come to an end. Using fgsea without nperm does also not work on my systems. However, using nperm = 1000 the calculation with the example data set works pretty fast again, but when I increase nperm to like 1001 or more the infinite loop starts.

R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS
fgsea_1.16.0 

Christian

**Comment by assaron** [comment]
Did I read it correct that for you it hangs on the example data? How about
if you set option nproc=1?

**Comment by ChristianRohde** [comment]
Yes indeed I was using the example data since I wanted to exclude that my data creates the trouble. Now with nproc=1 it works again.
